AWSTemplateFormatVersion: "2010-09-09"
Description: 'Sets up the subnet-protected SG'
Metadata: {}

Parameters:
    VpcName:
        Description: VPC Name
        Type: String
        Default: corp-datasys-prod

Resources:
    SgSubnetProtected:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: subnet-protected
            GroupDescription: subnet-protected security group
            VpcId:
                Fn::ImportValue: !Sub vpc-${VpcName}-VpcId
            Tags:
                - Key: Name
                  Value: subnet-protected
                - Key: name
                  Value: subnet-protected
                - Key: vpc
                  Value: !Ref VpcName

    EgressRule1:
        Type: AWS::EC2::SecurityGroupEgress
        Properties:
            GroupId: !Ref SgSubnetProtected
            IpProtocol: "-1"
            CidrIp: 127.0.0.1/32
            Description: Remove default egress 0.0.0.0/0

Outputs:

    StackName:
        Value: !Ref AWS::StackName

    SgSubnetProtectedId:
        Value: !Ref SgSubnetProtected
        Export:
            Name: sg-subnet-protected-id

