version: "3"

services:
  airflow:
    build:
      context: .
    ports:
      - "2000:8080"
    volumes:
      - ./airflow:/airflow
    command: >
      sh -c "python /Users/pmotwani/Desktop/bitcoin/myconversionproject/airflow/dags.py 0.0.0.0:8080"
  mysql:
    build:
      context: .
    ports:
      - "1000:3306"
    depends_on:
      - airflow
